/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class EnterUIUI extends Laya.View {
		public _Start:Laya.Button;
		public _Character:Laya.Button;
		public _Panel:Laya.Panel;
		public _SetPanel:Laya.Button;
		public _CharacterList:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("EnterUI");
        }
    }
    export class SetPanelUIUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("SetPanelUI");
        }
    }
}