/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class BGUI extends Laya.View {
		public _Earth:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("BG");
        }
    }
    export class CharacterUI extends Laya.View {
		public bg:Laya.Image;
		public _Gold:Laya.Label;
		public _List:Laya.List;
		public backBtn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Character");
        }
    }
    export class EndGameUI extends Laya.View {
		public bg:Laya.Sprite;
		public _StartBtn:Laya.Button;
		public _MenueBtn:Laya.Button;
		public _SetBtn:Laya.Button;
		public _PlayerListBtn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("EndGame");
        }
    }
    export class EnterUI extends Laya.View {
		public bg:Laya.Sprite;
		public _logo:Laya.Sprite;
		public _Start:Laya.Button;
		public _Character:Laya.Button;
		public _Panel:Laya.Panel;
		public _Group:Laya.Image;
		public _SetPanel:Laya.Button;
		public _CharacterList:Laya.Button;
		public adv:Laya.Button;
		public _Rank:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Enter");
        }
    }
    export class GameUI extends Laya.View {
		public _CountDownUI:Laya.Box;
		public _ItemListBtn:Laya.Button;
		public _CountTime:Laya.Label;
		public _GameInfo:Laya.Label;
		public _GamePanel:Laya.Box;
		public _TxtDistance:Laya.Label;
		public _TxtGold:Laya.Label;
		public _LeftTouch:Laya.Button;
		public _RightTouch:Laya.Button;
		public _SkillItem:Laya.Button;
		public _PlayerItem:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Game");
        }
    }
    export class GameRankUI extends Laya.View {
		public closeBtn:Laya.Button;
		public gameRankUi:laya.ui.WXOpenDataViewer;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameRank");
        }
    }
    export class ItemListUI extends Laya.View {
		public _BG:Laya.Image;
		public bg:Laya.Sprite;
		public _List:Laya.List;
		public backBtn:Laya.Button;
		public _Gold:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ItemList");
        }
    }
    export class PlayerListUI extends Laya.View {
		public _PlayerList:Laya.List;
		public _ReturnMain:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("PlayerList");
        }
    }
    export class SetPanelUI extends Laya.View {
		public bg:Laya.Image;
		public _Text:Laya.TextArea;
		public _Return:Laya.Button;
		public voiceopen:Laya.Box;
		public voiceclose:Laya.Box;
		public leftOptBtn:Laya.Button;
		public rightOpt:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("SetPanel");
        }
    }
}